# Generated by Django 5.0 on 2023-12-13 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Account",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="materials_provided",
            new_name="materials_provide",
        ),
    ]
