# Generated by Django 4.2.6 on 2023-11-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_outfit_product_outfit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='type',
            new_name='name',
        ),
    ]
