# Generated by Django 5.0 on 2023-12-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TravelPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination_name", models.CharField(max_length=50)),
                ("duration", models.IntegerField()),
                ("persons", models.IntegerField()),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="packages/images/")),
            ],
        ),
    ]
