# Generated by Django 4.2.6 on 2023-11-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalcost',
            field=models.IntegerField(default=0, verbose_name='Total Cost'),
        ),
    ]
